### PR TITLE
Login, Logout authentication

### PR DESCRIPTION
**Pull request by ainmutaqorrobin**

### CODE REVIEW

**Review by HafizMustaqim — COMMENTED** [review]
LGTM.
For next PR, pls put comment on your code. It's a good SE practices for our current teams and future developer to maintain this code.

**Review by HafizMustaqim — APPROVED** [review]

**Comment by HafizMustaqim** [comment]
who the other one that need to review this code?

**Comment by ainmutaqorrobin** [comment]
> LGTM. For next PR, pls put comment on your code. It's a good SE practices for our current teams and future developer to maintain this code.

there's 12 comment total for this PR, do you review all of the commit yet before comment sir?

**Comment by ainmutaqorrobin** [comment]
> who the other one that need to review this code?

myself

**Comment by HafizMustaqim** [comment]
> > LGTM. For next PR, pls put comment on your code. It's a good SE practices for our current teams and future developer to maintain this code.
> 
> there's 12 comment total for this PR, are you review all of the commit yet before comment sir?

when i say put, i expect more.

**Comment by ainmutaqorrobin** [comment]
> when i say put, i expect more.

This is not side notes, this is codebase

**Pull request merged**
